package com.obaba.erp.entities;
// Generated 25 Nov, 2018 1:41:19 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TLookUp generated by hbm2java
 */
@Entity
@Table(name = "t_look_up", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "look_up_name"))
public class TLookUp implements java.io.Serializable {

	private Integer id;
	private String lookUpName;
	private String lookUpValue;
	private Date createDate;
	private Date updateDate;

	public TLookUp() {
	}

	public TLookUp(String lookUpName, String lookUpValue) {
		this.lookUpName = lookUpName;
		this.lookUpValue = lookUpValue;
	}

	public TLookUp(String lookUpName, String lookUpValue, Date createDate, Date updateDate) {
		this.lookUpName = lookUpName;
		this.lookUpValue = lookUpValue;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "look_up_name", unique = true, nullable = false, length = 50)
	public String getLookUpName() {
		return this.lookUpName;
	}

	public void setLookUpName(String lookUpName) {
		this.lookUpName = lookUpName;
	}

	@Column(name = "look_up_value", nullable = false, length = 50)
	public String getLookUpValue() {
		return this.lookUpValue;
	}

	public void setLookUpValue(String lookUpValue) {
		this.lookUpValue = lookUpValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
