package com.obaba.erp.entities;
// Generated 24 Oct, 2018 12:07:49 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TLookUp generated by hbm2java
 */
@Entity
@Table(name = "t_look_up", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "look_up_name"))
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TLookUp implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "look_up_name", unique = true, nullable = false, length = 50)
	private String lookUpName;

	@Column(name = "look_up_value", nullable = false, length = 50)
	private String lookUpValue;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;

}
