package com.obaba.erp.entities;
// Generated 24 Oct, 2018 12:07:49 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrderDetails generated by hbm2java
 */
@Entity
@Table(name = "t_order_details", catalog = "demo")
public class TOrderDetails implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	private TOrders TOrders;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	private TProducts TProducts;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "item_price", nullable = false)
	private int itemPrice;

	@Column(name = "quantity", nullable = false)
	private int quantity;
	
	@Column(name = "description", nullable = false)
	private String description;
	
	@Column(name = "free_shipping", nullable = false, length = 1)
	private char freeShipping;

	@Column(name = "is_delivered", nullable = false, length = 1)
	private char isDelivered;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	private Date createdDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;

	@Column(name = "created_by")
	private Integer createdBy;

	@Column(name = "updated_by")
	private Integer updatedBy;

}
