package com.obaba.erp.entities;
// Generated 25 Nov, 2018 1:41:19 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrderDetails generated by hbm2java
 */
@Entity
@Table(name = "t_order_details", catalog = "demo")
public class TOrderDetails implements java.io.Serializable {

	private Integer id;
	private TOrders TOrders;
	private TProducts TProducts;
	private String name;
	private int itemPrice;
	private int quantity;
	private String description;
	private char freeShipping;
	private char isDelivered;
	private Date createdDate;
	private Date updateDate;
	private Integer createdBy;
	private Integer updatedBy;

	public TOrderDetails() {
	}

	public TOrderDetails(TOrders TOrders, TProducts TProducts, String name, int itemPrice, int quantity,
			String description, char freeShipping, char isDelivered) {
		this.TOrders = TOrders;
		this.TProducts = TProducts;
		this.name = name;
		this.itemPrice = itemPrice;
		this.quantity = quantity;
		this.description = description;
		this.freeShipping = freeShipping;
		this.isDelivered = isDelivered;
	}

	public TOrderDetails(TOrders TOrders, TProducts TProducts, String name, int itemPrice, int quantity,
			String description, char freeShipping, char isDelivered, Date createdDate, Date updateDate,
			Integer createdBy, Integer updatedBy) {
		this.TOrders = TOrders;
		this.TProducts = TProducts;
		this.name = name;
		this.itemPrice = itemPrice;
		this.quantity = quantity;
		this.description = description;
		this.freeShipping = freeShipping;
		this.isDelivered = isDelivered;
		this.createdDate = createdDate;
		this.updateDate = updateDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public TOrders getTOrders() {
		return null;
	}

	public void setTOrders(TOrders TOrders) {
		this.TOrders = TOrders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public TProducts getTProducts() {
		return null;
	}

	public void setTProducts(TProducts TProducts) {
		this.TProducts = TProducts;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "item_price", nullable = false)
	public int getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(int itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "free_shipping", nullable = false, length = 1)
	public char getFreeShipping() {
		return this.freeShipping;
	}

	public void setFreeShipping(char freeShipping) {
		this.freeShipping = freeShipping;
	}

	@Column(name = "is_delivered", nullable = false, length = 1)
	public char getIsDelivered() {
		return this.isDelivered;
	}

	public void setIsDelivered(char isDelivered) {
		this.isDelivered = isDelivered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
