package com.obaba.erp.entities;
// Generated 24 Oct, 2018 12:07:49 AM by Hibernate Tools 5.2.10.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TOrders generated by hbm2java
 */
@Entity
@Table(name = "t_orders", catalog = "demo")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TOrders implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private TUser TUser;

	@Column(name = "total_price", nullable = false)
	private int totalPrice;

	@Column(name = "item_count")
	private Integer itemCount;

	@Column(name = "free_shipping", length = 1)
	private Character freeShipping;

	@Column(name = "payment_type", length = 50)
	private String paymentType;

	@Column(name = "order_status", length = 55)
	private String orderStatus;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;

	@Column(name = "created_by")
	private Integer createdBy;

	@Column(name = "updated_by")
	private Integer updatedBy;

	@OneToMany(cascade = CascadeType.ALL, fetch=FetchType.EAGER)
	@JoinColumn(name = "order_id", referencedColumnName = "id")
	private List<TOrderDetails> TOrderDetailses = new ArrayList<TOrderDetails>();

}
