package com.obaba.erp.entities;
// Generated 7 Oct, 2018 12:45:47 AM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

/**
 * TProductCategory generated by hbm2java
 */
@Entity
@Table(name = "t_product_category", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "category_name"))
@Data
public class TProductCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4663584067191895192L;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	private Integer categoryId;
	
	@Column(name = "category_name", unique = true, nullable = false)
	private String categoryName;
	
	@Column(name = "category_desc")
	private String categoryDesc;
	
	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;
	
	@JsonIgnore
	@Column(name = "created_by")
	private Integer createdBy;
	
	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;
	
	@JsonIgnore
	@Column(name = "updated_by")
	private Integer updatedBy;
	
	/*@OneToMany(fetch = FetchType.EAGER, mappedBy = "productCategory" )
	private List<TProductSubCategory> productSubCategories ;
	*/
	
	@OneToMany(cascade = CascadeType.ALL, fetch=FetchType.EAGER)
	@JoinColumn(name = "category_id", referencedColumnName = "category_id")
	private Set<TProductSubCategory> productSubCategories ;
	
}
