package com.obaba.erp.entities;
// Generated 7 Oct, 2018 12:45:47 AM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.google.gson.annotations.Expose;

import lombok.Data;

/**
 * TProductSubCategory generated by hbm2java
 */
@Entity
@Table(name = "t_product_sub_category", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "sub_category_name"))
@Data
public class TProductSubCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7946515455348061760L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sub_category_id", nullable = true)
	@Expose
	private Integer subCategoryId;
	
	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	private TProductCategory productCategory;*/
	
	@Column(name = "category_id" ,  nullable = true)
	@Expose
	private Integer categoryID;
	
	@Expose
	@Column(name = "sub_category_name", unique = true, nullable = false)
	private String subCategoryName;
	
	@Expose
	@Column(name = "sub_category_desc")
	private String subCategoryDesc;
	
	@Expose
	@Column(name = "image_url")
	private String imageUrl;
	
	//@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;
	
	//@JsonIgnore
	@Column(name = "created_by")
	private String createdBy;
	
	//@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;
	
	//@JsonIgnore
	@Column(name = "updated_by")
	private String updatedBy;
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tProductSubCategoryByProductCategoryId")
	private List<TProducts> TProductsesCategoryId ;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tProductSubCategoryByProductSubCategoryId")
	private List<TProducts> TProductsesSubCategoryId ;*/

	
	
}
