package com.obaba.erp.entities;
// Generated 7 Oct, 2018 12:45:47 AM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

import lombok.Data;

/**
 * TProducts generated by hbm2java
 */
@Entity
@Table(name = "t_products", catalog = "demo")
@Data
public class TProducts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	@Expose
	private Integer productId;

	/*@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_category_id", nullable = false)
	private TProductSubCategory tProductSubCategoryByProductCategoryId;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_sub_category_id", nullable = false)
	private TProductSubCategory tProductSubCategoryByProductSubCategoryId;*/
	
	@Column(name = "product_category_id", nullable = true)
	@Expose
	private Integer productcategoryID;
	
	@Column(name = "product_sub_category_id" , nullable = true)
	@Expose
	private Integer productSubCategoryID;
	
	@Column(name = "product_product_sku", length = 20)
	@Expose
	private String productProductSku;
	
	@Column(name = "product_name", length = 100)
	@Expose
	private String productName;
	
	@Column(name = "product_brand", length = 30)
	@Expose
	private String productBrand;
	
	@Column(name = "product_color", length = 20)
	@Expose
	private String productColor;
	
	@Column(name = "product_size", length = 50)
	@Expose
	private String productSize;
	
	@Column(name = "product_price")
	@Expose
	private Integer productPrice;
	
	@Column(name = "product_image", length = 100)
	@Expose
	private String productImage;
	
	@Column(name = "product_quantity")
	@Expose
	private Integer productQuantity;
	
	//@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;
	
	//@JsonIgnore
	@Column(name = "created_by")
	private Integer createdBy;
	
	//@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;
	
	//@JsonIgnore
	@Column(name = "updated_by")
	private Integer updatedBy;
	
	@Expose
	@Column(name = "is_active", nullable = true)
	private char isActive;
	
	@Expose
	@Column(name = "is_home", nullable = true )
	private char isHome;

}
