package com.obaba.erp.entities;
// Generated 6 Oct, 2018 1:15:13 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TProductSubCategory generated by hbm2java
 */
@Entity
@Table(name = "t_product_sub_category", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "sub_category_name"))
public class TProductSubCategory implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sub_category_id", unique = true, nullable = false)
	private Integer subCategoryId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	private TProductCategory TProductCategory;

	@Column(name = "sub_category_name", unique = true, nullable = false)
	private String subCategoryName;

	@Column(name = "sub_category_desc")
	private String subCategoryDesc;

	@Column(name = "image_url")
	private String imageUrl;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;

	@Column(name = "created_by")
	private String createdBy;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	private Date updateDate;

	@Column(name = "updated_by")
	private String updatedBy;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "TProductSubCategory")
	private Set<TProducts> TProductses = new HashSet<TProducts>(0);

	public TProductSubCategory() {
	}
	

	public TProductSubCategory(TProductCategory TProductCategory, String subCategoryName) {
		this.TProductCategory = TProductCategory;
		this.subCategoryName = subCategoryName;
	}

	public TProductSubCategory(TProductCategory TProductCategory, String subCategoryName, String subCategoryDesc,
			String imageUrl, Date createDate, String createdBy, Date updateDate, String updatedBy,
			Set<TProducts> TProductses) {
		this.TProductCategory = TProductCategory;
		this.subCategoryName = subCategoryName;
		this.subCategoryDesc = subCategoryDesc;
		this.imageUrl = imageUrl;
		this.createDate = createDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updatedBy = updatedBy;
		this.TProductses = TProductses;
	}

	public Integer getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public TProductCategory getTProductCategory() {
		return this.TProductCategory;
	}

	public void setTProductCategory(TProductCategory TProductCategory) {
		this.TProductCategory = TProductCategory;
	}

	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	public String getSubCategoryDesc() {
		return this.subCategoryDesc;
	}

	public void setSubCategoryDesc(String subCategoryDesc) {
		this.subCategoryDesc = subCategoryDesc;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set<TProducts> getTProductses() {
		return this.TProductses;
	}

	public void setTProductses(Set<TProducts> TProductses) {
		this.TProductses = TProductses;
	}

}
