package com.obaba.erp.entities;
// Generated 25 Nov, 2018 1:41:19 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", catalog = "demo", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class TUser implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private char isActive;
	private Date createDate;
	private Date updateDate;
	private Integer createdBy;
	private Integer updatedBy;
	private Set<TWishlist> TWishlists = new HashSet<TWishlist>(0);
	private Set<TOrders> TOrderses = new HashSet<TOrders>(0);
	private Set<TCart> TCarts = new HashSet<TCart>(0);

	public TUser() {
	}

	public TUser(char isActive) {
		this.isActive = isActive;
	}

	public TUser(String username, String password, char isActive, Date createDate, Date updateDate, Integer createdBy,
			Integer updatedBy, Set<TWishlist> TWishlists, Set<TOrders> TOrderses, Set<TCart> TCarts) {
		this.username = username;
		this.password = password;
		this.isActive = isActive;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.TWishlists = TWishlists;
		this.TOrderses = TOrderses;
		this.TCarts = TCarts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", unique = true)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TWishlist> getTWishlists() {
		return this.TWishlists;
	}

	public void setTWishlists(Set<TWishlist> TWishlists) {
		this.TWishlists = TWishlists;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TOrders> getTOrderses() {
		return this.TOrderses;
	}

	public void setTOrderses(Set<TOrders> TOrderses) {
		this.TOrderses = TOrderses;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TCart> getTCarts() {
		return this.TCarts;
	}

	public void setTCarts(Set<TCart> TCarts) {
		this.TCarts = TCarts;
	}

}
