package com.obaba.erp.entities;
// Generated 25 Nov, 2018 1:41:19 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TWishlist generated by hbm2java
 */
@Entity
@Table(name = "t_wishlist", catalog = "demo")
public class TWishlist implements java.io.Serializable {

	private Integer id;
	private TProducts TProducts;
	private TUser TUser;
	private Date createDate;
	private Date updateDate;
	private Byte createdBy;
	private Byte updatedBy;
	private Character isActive;

	public TWishlist() {
	}

	public TWishlist(TProducts TProducts, TUser TUser) {
		this.TProducts = TProducts;
		this.TUser = TUser;
	}

	public TWishlist(TProducts TProducts, TUser TUser, Date createDate, Date updateDate, Byte createdBy, Byte updatedBy,
			Character isActive) {
		this.TProducts = TProducts;
		this.TUser = TUser;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public TProducts getTProducts() {
		return null;
	}

	public void setTProducts(TProducts TProducts) {
		this.TProducts = TProducts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TUser getTUser() {
		return null;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "created_by")
	public Byte getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Byte createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Byte getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Byte updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "is_active", length = 1)
	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

}
